package com.lvbby.codema.app.mysql;

import com.alibaba.druid.sql.SQLUtils;
import com.alibaba.druid.sql.ast.SQLExpr;
import com.alibaba.druid.sql.ast.SQLStatement;
import com.alibaba.druid.sql.ast.expr.SQLCharExpr;
import com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr;
import com.alibaba.druid.sql.ast.statement.SQLInsertStatement;
import com.alibaba.druid.util.JdbcConstants;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.lvbby.codema.core.AbstractBaseMachine;
import com.lvbby.codema.core.Codema;
import com.lvbby.codema.core.Machine;
import com.lvbby.codema.core.handler.ResultHandlerFactory;
import com.lvbby.codema.core.result.BasicResult;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.Validate;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 *
 * @author dushang.lp
 * @version $Id: InsertFormatMachine.java, v 0.1 2018年05月31日 上午10:52 dushang.lp Exp $
 */
public class InsertFormatMachine extends AbstractBaseMachine<String, String> {
    private List<String> excludeColumns;
    private Map<String, Object> columnHandlers = Maps.newHashMap();

    @Override protected void doCode() throws Exception {
        excludeColumns = excludeColumns.stream().map(String::toLowerCase).collect(Collectors.toList());
        List<SQLStatement> sqlStatements = SQLUtils.parseStatements(source, JdbcConstants.MYSQL);
        sqlStatements.stream().forEach(sqlStatement -> {
            Validate.isTrue(sqlStatement instanceof SQLInsertStatement);
            SQLInsertStatement insert = (SQLInsertStatement) sqlStatement;
            if (CollectionUtils.isNotEmpty(excludeColumns)) {
                List<SQLExpr> columns = insert.getColumns();
                List<SQLExpr> values = insert.getValues().getValues();
                List<Integer> excludeIndex = Lists.reverse(
                        columns.stream().filter(sqlExpr -> excludeColumns.contains(sqlExpr.toString().toLowerCase()))
                                .map(sqlExpr -> columns.indexOf(sqlExpr)).collect(Collectors.toList()));
                //删除排除的列
                excludeIndex.forEach(index -> {
                    columns.remove((int) index);
                    values.remove((int) index);
                });
            }
            if (!columnHandlers.isEmpty()) {
                List<SQLExpr> columns = insert.getColumns();
                List<SQLExpr> values = insert.getValues().getValues();
                for (int i = 0; i < columns.size(); i++) {
                    String col = columns.get(i).toString();
                    Object replace = columnHandlers.get(col);
                    if (replace != null) {
                        if (replace instanceof SQLExpr) {
                            values.set(i, (SQLExpr) replace);
                        } else {
                            values.set(i, new SQLCharExpr(replace.toString()));
                        }
                    }
                }
            }
        });
        handle(BasicResult.instance(sqlStatements.stream().map(SQLStatement::toString).collect(Collectors.joining("\n"))));
    }

    public InsertFormatMachine excludeColumn(String column) {
        if (excludeColumns == null)
            excludeColumns = Lists.newArrayList();
        excludeColumns.add(column);
        return this;
    }

    public InsertFormatMachine addHandler(String column, Object value) {
        columnHandlers.put(column, value);
        return this;
    }

    /**
     * Getter method for property   excludeColumns.
     *
     * @return property value of excludeColumns
     */
    public List<String> getExcludeColumns() {
        return excludeColumns;
    }

    /**
     * Setter method for property   excludeColumns .
     *
     * @param excludeColumns  value to be assigned to property excludeColumns
     */
    public void setExcludeColumns(List<String> excludeColumns) {
        this.excludeColumns = excludeColumns;
    }

    public static void main(String[] args) throws Exception {
        String s = "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(9, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'APPLY_AMOUNT', 'MIN_VALUE', '1', '最小值校验', 'USER_CREATE_CONTRACT_ORDER', null, 2, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(10, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'APPLY_AMOUNT', 'MONEY', '^(?!0+(\\\\.0+)?$)([1-9]\\\\d*|0)(\\\\.\\\\d{1,2})?$', 'money格式校验', 'USER_CREATE_CONTRACT_ORDER', null, 1, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(8, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'APPLY_AMOUNT', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(130, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'APPLY_AMOUNT', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(55, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'APPLY_AMOUNT', 'MIN_VALUE', '1', '最小值校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(56, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'APPLY_AMOUNT', 'MONEY', '^(?!0+(\\\\.0+)?$)([1-9]\\\\d*|0)(\\\\.\\\\d{1,2})?$', 'money格式校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(54, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'APPLY_AMOUNT', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(14, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'APPLY_TIME', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(123, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'APPLY_TIME', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(60, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'APPLY_TIME', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(16, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'BANK_CARD_SIGNID', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(131, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'BANK_CARD_SIGNID', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(62, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'BANK_CARD_SIGNID', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(95, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'CONTRACT_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(191, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'CONTRACT_ID', 'NULLABLE', 'Y', '参数非空校验', 'USER_CAPITAL_PLAN_DETAIL_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(115, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'CONTRACT_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(46, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'CONTRACT_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(100, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'ENVIRONMENT', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(195, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'ENVIRONMENT', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_DETAIL_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(178, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'ENVIRONMENT', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_LIST_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(5, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'ENVIRONMENT', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(121, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'ENVIRONMENT', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(164, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'ENVIRONMENT', 'NULLABLE', 'N', '参数非空校验', 'USER_HAS_CAPITAL_PLAN_ORDERS', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(51, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'ENVIRONMENT', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(13, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FIXED_DAY', 'MAX_VALUE', '28', '最大值校验', 'USER_CREATE_CONTRACT_ORDER', null, 1, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(12, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FIXED_DAY', 'MIN_VALUE', '1', '最小值校验', 'USER_CREATE_CONTRACT_ORDER', null, 1, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(11, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FIXED_DAY', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(128, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'FIXED_DAY', 'MAX_VALUE', '28', '最大值校验', 'USER_DELETE_CONTRACT_ORDER', null, 1, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(127, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'FIXED_DAY', 'MIN_VALUE', '1', '最小值校验', 'USER_DELETE_CONTRACT_ORDER', null, 1, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(126, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'FIXED_DAY', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(59, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FIXED_DAY', 'MAX_VALUE', '28', '最大值校验', 'USER_MODIFY_CONTRACT_ORDER', null, 1, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(58, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FIXED_DAY', 'MIN_VALUE', '1', '最小值校验', 'USER_MODIFY_CONTRACT_ORDER', null, 1, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(57, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FIXED_DAY', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(15, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FIXED_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(122, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'FIXED_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(61, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FIXED_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(18, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FREEZE_CODE', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(129, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'FREEZE_CODE', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(65, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'FREEZE_CODE', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(1, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'INST_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(117, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'INST_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(47, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'INST_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(7, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'PAY_CHANNEL', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(124, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'PAY_CHANNEL', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(53, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'PAY_CHANNEL', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(6, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'PAY_CHANNEL_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(125, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'PAY_CHANNEL_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(52, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'PAY_CHANNEL_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(99, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'PRINCIPAL', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(194, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'PRINCIPAL', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_DETAIL_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(177, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'PRINCIPAL', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_LIST_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(4, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'PRINCIPAL', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(120, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'PRINCIPAL', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(163, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'PRINCIPAL', 'NULLABLE', 'N', '参数非空校验', 'USER_HAS_CAPITAL_PLAN_ORDERS', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(50, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'PRINCIPAL', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(98, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'SCENE_PLAN_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(193, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'SCENE_PLAN_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_DETAIL_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(176, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'SCENE_PLAN_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_LIST_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(17, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'SCENE_PLAN_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(119, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'SCENE_PLAN_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(162, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'SCENE_PLAN_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_HAS_CAPITAL_PLAN_ORDERS', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(63, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'SCENE_PLAN_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(97, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(3, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(118, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(49, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(181, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'STATUS_LIST', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_LIST_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(167, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'STATUS_LIST', 'NULLABLE', 'N', '参数非空校验', 'USER_HAS_CAPITAL_PLAN_ORDERS', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(96, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'USER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(192, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'USER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_DETAIL_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(175, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'USER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_LIST_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(2, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'USER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(116, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'USER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(161, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'USER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_HAS_CAPITAL_PLAN_ORDERS', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(48, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'USER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(101, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_EXT_INFO', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(22, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'YEB_EXT_INFO', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(132, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_EXT_INFO', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(64, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'YEB_EXT_INFO', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(21, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'YEB_FIXED_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(137, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_FIXED_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(69, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'YEB_FIXED_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(182, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'YEB_IS_QUERY_AMOUNT', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_LIST_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(103, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_ORDER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(197, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'YEB_ORDER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_DETAIL_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(134, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_ORDER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(66, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'YEB_ORDER_ID', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(136, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_ORDER_STATUS', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(104, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_ORDER_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(180, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'YEB_ORDER_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_LIST_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(19, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'YEB_ORDER_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(135, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_ORDER_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(166, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'YEB_ORDER_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_HAS_CAPITAL_PLAN_ORDERS', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(67, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'YEB_ORDER_TYPE', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(102, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_CANCEL_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(196, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'YEB_SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_DETAIL_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(179, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'YEB_SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_CAPITAL_PLAN_LIST_QUERY', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(20, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'YEB_SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_CREATE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(133, '2018-05-31 14:04:39', '2018-05-31 14:04:39', 'RHT_IN', 'YEB_SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_DELETE_CONTRACT_ORDER', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(165, '2018-05-31 14:04:40', '2018-05-31 14:04:40', 'RHT_IN', 'YEB_SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_HAS_CAPITAL_PLAN_ORDERS', null, 0, null);\n"
                   + "insert into `finpwm_cpm_product_element_cstr`( id,  gmt_create,  gmt_modified,  product_code,  element_code,  cstr_type,  cstr_value,  cstr_content,  operate_code,  ext_info,  priority,  groovy_rule) values(68, '2018-05-31 14:04:38', '2018-05-31 14:04:38', 'RHT_IN', 'YEB_SOURCE_FROM', 'NULLABLE', 'N', '参数非空校验', 'USER_MODIFY_CONTRACT_ORDER', null, 0, null);\n";
        SQLIdentifierExpr current_timestamp = new SQLIdentifierExpr("CURRENT_TIMESTAMP");
        Machine m = new InsertFormatMachine().excludeColumn("id")
                .addHandler("gmt_create", current_timestamp)
                .addHandler("gmt_modified", current_timestamp)
                .addHandler("product_code", "WFIN")
                .source(s);
        Codema.exec(Lists.newArrayList(ResultHandlerFactory.print,ResultHandlerFactory.clipBoard),m);
    }

}